name: asan
on:
  pull_request:
  schedule:
    - cron: '23 0 * * *'
  workflow_dispatch:

jobs:
  build_and_test:
    name: rmf_traffic-asan
    uses: open-rmf/rmf_ci_templates/.github/workflows/reusable_asan.yaml@main
    with:
      dist-matrix: |
          [{"ros_distribution": "humble",
            "ubuntu_distribution": "jammy"}]
      # NOTE: Avoid adding comments in the package lines, this can break some of the called scripts in github actions
      packages: |
        rmf_traffic
        rmf_traffic_examples
